#pragma once


#define SERIAL_STREAM Serial

#define SERIAL_BAUDRATE 115200

#define ACTIVE_REPORT_MILLIS 50

#define IDLE_REPORT_MILLIS 500

#define RX_BUFFER_SIZE 256

#define MESSAGE_BUFFER_SIZE 256

#define ARG_BUFFER_SIZE 16

#define CMD_CHAR_MAX 5

#define MAX_USER_COMMANDS 25

#define MAX_USER_CALLBACKS 10

#define CMD_MAX_ARGS 10

#define CMD_DELIMITER ":"

#define ARG_DELIMITER_CHAR ','

#define ARG_SKIP_CHAR '*'

#define MAX_STEPPERS 6

#define SIN_CURVE_ACCELERATION false

#define PULSE_WIDTH_US 4

#define HOMING_OVERSHOOT 2.0

#define PROBING_OVERSHOOT 2.0

#define MAX_EVENT_CALLBACKS 20


// #define HOME_STEPPERS_FIRST